### ISSUE TITLE
RDF export runtime dependency error

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-tag#49]
```
org.apache.jena.shared.NoWriterForLangException: Writer not found: TURTLE
	at org.apache.jena.core@4.4.0/org.apache.jena.rdf.model.impl.RDFWriterFImpl.getWriter(RDFWriterFImpl.java:66)
	at org.apache.jena.core@4.4.0/org.apache.jena.rdf.model.impl.ModelCom.getWriter(ModelCom.java:272)
	at org.apache.jena.core@4.4.0/org.apache.jena.rdf.model.impl.ModelCom.write(ModelCom.java:285)
	at sniktag@22.05/eu.snik.tag.gui.MainMenuBar.lambda$fileMenu$4(MainMenuBar.java:142)
	at javafx.base@18/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.controls@18/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
	at javafx.controls@18/com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$2(ControlAcceleratorSupport.java:190)
	at javafx.graphics@18/com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:382)
	at javafx.graphics@18/com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:162)
	at javafx.base@18/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18/javafx.scene.Scene$KeyHandler.process(Scene.java:4089)
	at javafx.graphics@18/javafx.scene.Scene.processKeyEvent(Scene.java:2146)
	at javafx.graphics@18/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2614)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@18/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)
	at javafx.graphics@18/com.sun.glass.ui.View.handleKeyEvent(View.java:542)
	at javafx.graphics@18/com.sun.glass.ui.View.notifyKey(View.java:966)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by Yagnap** [comment]
I don't think that will fix this, but the Model.write() we are using at the moment to write the RDF seems to only be still included for legacy reasons: https://github.com/apache/jena/issues/2300#issuecomment-1969011135 with the new suggested way being "RDFDataMgr": https://jena.apache.org/documentation/io/rdf-output.html#api, but switching that should be simple.

**Comment by KonradHoeffner** [comment]
@Yagnap: Thanks! Do you want to refactor it to the RDFDataMgr or would you prefer if I implement that?

**Comment by Yagnap** [comment]
I implemented it, and it seems to work now. Pushing in a minute
